/*
	Autogenerated folder includes for xcf/client
*/

if not aaa_foldergen_wasloaded then include("autorun/aaa_foldergen.lua") end

// Requires manual sorting.
//include("xcf/client/test_controls.lua")
include("xcf/client/xcf_sanitize_acf_table_cl.lua")
include("xcf/client/xcf_permission_cl.lua")
include("xcf/client/xcf_ballistics_cl.lua")
include("xcf/client/xcf_neteffects_cl.lua")
include("xcf/client/xcf_baseproj_cl.lua")

aaa_IncludeHere("xcf/client/gui")
aaa_IncludeHere("xcf/client/projectiles")