/*
	Autogenerated folder includes for autorun/shared
*/

if not aaa_foldergen_wasloaded then include("autorun/aaa_foldergen.lua") end

// Requires manual sorting.
AddCSLuaFile("autorun/xcf_includes_sh.lua")


AddCSLuaFile("autorun/printbyname.lua")
include("autorun/printbyname.lua")

AddCSLuaFile("autorun/xcf_classbase_sh.lua")
include("autorun/xcf_classbase_sh.lua")