/*
	Autogenerated folder includes for xcf/client
*/

if not aaa_foldergen_wasloaded then include("autorun/aaa_foldergen.lua") end

// Requires manual sorting.
include("xcf/shared/xcf_acf_additions.lua")

include("autorun/client/drawarc.lua")

aaa_IncludeHere("xcf/shared/gunclass")

include("xcf/shared/xcf_missiledefs_shared.lua")
include("xcf/shared/xcf_missilefuncs_shared.lua")

include("xcf/client/xcf_util_cl.lua")
include("xcf/client/xcf_sanitize_acf_table_cl.lua")
//include("xcf/client/xcf_permission_cl.lua")
include("xcf/client/xcf_ballistics_cl.lua")
include("xcf/client/xcf_neteffects_cl.lua")

include("xcf/shared/xcf_baseproj_sh.lua")
include("xcf/client/xcf_baseproj_cl.lua")



aaa_IncludeHere("xcf/shared/projectiles")
aaa_IncludeHere("xcf/client/projectiles")

aaa_IncludeHere("xcf/client/gui")

include("xcf/client/cl_xcftab_gui.lua")




// Requires manual sorting.

