/*
	Autogenerated folder includes for xcf/shared
*/

if not aaa_foldergen_wasloaded then include("autorun/aaa_autoincludes.lua") end

// Requires manual sorting.
AddCSLuaFile("xcf/shared/aaa_folder.lua")

AddCSLuaFile("xcf/shared/xcf_acf_additions.lua")
include("xcf/shared/xcf_acf_additions.lua")

AddCSLuaFile("xcf/shared/xcf_util_sh.lua")
include("xcf/shared/xcf_util_sh.lua")

AddCSLuaFile("xcf/shared/xcf_baseproj_sh.lua")
include("xcf/shared/xcf_baseproj_sh.lua")

AddCSLuaFile("xcf/shared/xcf_neteffects_sh.lua")
include("xcf/shared/xcf_neteffects_sh.lua")

AddCSLuaFile("xcf/shared/xcf_missiledefs_shared.lua")
include("xcf/shared/xcf_missiledefs_shared.lua")

AddCSLuaFile("xcf/shared/xcf_missilefuncs_shared.lua")
include("xcf/shared/xcf_missilefuncs_shared.lua")


aaa_IncludeShared("xcf/shared/gunclass")
aaa_IncludeShared("xcf/shared/projectiles")
