/*
	Autogenerated folder includes for xcf/server
*/

if not aaa_foldergen_wasloaded then include("autorun/aaa_foldergen.lua") end

// Requires manual sorting.
include("xcf/server/xcf_ballistics_sv.lua")
include("xcf/server/xcf_baseproj_sv.lua")
include("xcf/server/xcf_neteffects_sv.lua")
include("xcf/server/xcf_overrides_sv.lua")
include("xcf/server/xcf_permission_sv.lua")
include("xcf/server/xcf_commands_sv.lua")

aaa_IncludeHere("xcf/server/projectiles")
//aaa_IncludeHere("xcf/server/permissionmodes")