/*
	Autogenerated folder includes for xcf/server
*/

if not aaa_foldergen_wasloaded then include("autorun/aaa_autoincludes.lua") end

// Requires manual sorting.
include("xcf/shared/xcf_acf_additions.lua")

include("xcf/server/xcf_util_sv.lua")
include("xcf/server/xcf_permission_sv.lua")
include("xcf/server/xcf_ballistics_sv.lua")
include("xcf/server/xcf_neteffects_sv.lua")

include("xcf/shared/xcf_missiledefs_shared.lua")
include("xcf/shared/xcf_missilefuncs_shared.lua")

include("xcf/shared/xcf_baseproj_sh.lua")
include("xcf/server/xcf_baseproj_sv.lua")


aaa_IncludeHere("xcf/shared/gunclass")
aaa_IncludeHere("xcf/shared/projectiles")

aaa_IncludeHere("xcf/server/projectiles")
aaa_IncludeHere("xcf/server/permissionmodes")
